; PlatformIO Project Configuration File

[platformio]
default_envs = main_controller

[env:main_controller]
platform = espressif32
board = featheresp32
framework = espidf
build_flags =
    -DMAIN_CONTROLLER
board_upload.flash_size = 4MB
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 921600
lib_deps = ArduinoJson@^6.21.3
board_build.partitions = partitions.csv

[env:hmi]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
build_flags =
    -DHMI_CONTROLLER
board_build.cmake_extra_args =
    -DHMI_CONTROLLER=ON
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 921600
lib_deps =
    lvgl/lvgl@^8.3.11
    ArduinoJson@^6.21.3
