; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = main_controller

[env:main_controller]
platform = espressif32
board = featheresp32
framework = espidf
build_flags =
			-DMAIN_CONTROLLER
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 921600
lib_deps = ArduinoJson@^6.21.3
board_build.partitions = partitions.csv

[env:hmi]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
build_flags = 
	-DHMI_CONTROLLER
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 921600
lib_deps = 
	lvgl/lvgl@^8.3.11
	ArduinoJson@^6.21.3
